"use client";

import { useCallback, useEffect, useState } from "react";
import { platform } from "@/lib/platform";
import { readAccessToken } from "@/lib/auth-token";

type Company = { id: number; name: string; registration_number: string | null; status: string; currency: string; settings: { trading_name?: string } | null };

export default function OperatorApprovalsPage() {
  const [companies, setCompanies] = useState<Company[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const headers = useCallback(() => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${readAccessToken()}` }), []);
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`${platform.apiUrl}/management/companies/records`, { headers: headers() }); const body = await response.json(); setLoading(false); if (!response.ok) return setMessage(body.message ?? "Unable to load operator applications."); setCompanies(body.data ?? []); }, [headers]);
  useEffect(() => { queueMicrotask(load); }, [load]);
  async function decide(company: Company, decision: "approved" | "rejected" | "information_requested") { const reason = decision === "approved" ? null : window.prompt("Reason for this decision"); if (decision !== "approved" && !reason) return; const response = await fetch(`${platform.apiUrl}/operator-applications/${company.id}/decision`, { method: "POST", headers: headers(), body: JSON.stringify({ decision, reason, commission_rate: decision === "approved" ? 10 : null }) }); const body = await response.json(); setMessage(response.ok ? `${company.name}: ${decision.replaceAll("_", " ")}.` : body.message ?? "Decision failed."); if (response.ok) await load(); }
  return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="bg-[#0c312d] px-5 py-10 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.22em] text-[#ffce54]">Platform compliance</p><h1 className="mt-2 text-4xl font-black">Operator applications</h1><p className="mt-3 text-emerald-50/70">Review submitted operators and send decisions directly to the Laravel approval workflow.</p></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">{message && <p className="mb-5 rounded-2xl bg-white p-4 text-sm">{message}</p>}<div className="grid gap-4">{companies.map((company) => <article key={company.id} className="flex flex-col justify-between gap-5 rounded-3xl bg-white p-6 shadow-sm md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{company.registration_number ?? "No registration"}</p><h2 className="mt-2 text-2xl font-black">{company.settings?.trading_name || company.name}</h2><p className="mt-1 text-sm text-slate-500">{company.name} · {company.currency} · <span className="capitalize">{company.status.replaceAll("_", " ")}</span></p></div>{company.status === "under_review" && <div className="flex flex-wrap gap-2"><button onClick={() => decide(company, "information_requested")} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Request information</button><button onClick={() => decide(company, "rejected")} className="rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-800">Reject</button><button onClick={() => decide(company, "approved")} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">Approve</button></div>}</article>)}</div>{!companies.length && <p className="rounded-3xl border border-dashed border-slate-300 p-12 text-center text-slate-500">{loading ? "Loading operators…" : "No operators are visible for this account."}</p>}</div></main>;
}
