"use client";

/* eslint-disable @next/next/no-location-assign-relative-destination -- account lifecycle actions require a full document reload after clearing credentials */

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { clearAccessToken, readAccessToken } from "@/lib/auth-token";
import { platform } from "@/lib/platform";

type User = { name: string; email: string; phone: string | null; email_verified_at: string | null; phone_verified_at: string | null; two_factor_confirmed_at: string | null; language: string; currency: string; timezone: string };
type RecordItem = { id: number; name: string | null; code: string | null; status: string; data: Record<string, unknown> | null };
type Device = { id: number; name: string; last_used_at: string | null; current: boolean };
type Tab = "profile" | "documents" | "preferences" | "notifications" | "security" | "privacy";
type ApiBody = { message: string; errors: Record<string, string[]>; data?: unknown; secret: string; [key: string]: unknown };

const tabs: { key: Tab; label: string; description: string }[] = [
  { key: "profile", label: "Personal profile", description: "Identity, photograph and emergency contact" },
  { key: "documents", label: "Travel documents", description: "Saved identification and passport details" },
  { key: "preferences", label: "Travel preferences", description: "Seat, routes, operators and accessibility" },
  { key: "notifications", label: "Notifications", description: "Email, SMS and push preferences" },
  { key: "security", label: "Security & devices", description: "Verification, 2FA and active sessions" },
  { key: "privacy", label: "Privacy & account", description: "Export, deactivate or request deletion" },
];
const card = "grid gap-5 rounded-3xl bg-white p-6 shadow-sm";
const input = "min-h-12 rounded-xl border border-slate-300 bg-white px-4 text-sm outline-none focus:border-emerald-700 focus:ring-4 focus:ring-emerald-700/10";

export function PassengerAccount() {
  const token = readAccessToken();
  const [tab, setTab] = useState<Tab>("profile");
  const [user, setUser] = useState<User | null>(null);
  const [records, setRecords] = useState<Record<string, RecordItem[]>>({});
  const [devices, setDevices] = useState<Device[]>([]);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const headers = useCallback((json = true): HeadersInit => ({ Accept: "application/json", Authorization: `Bearer ${token}`, ...(json ? { "Content-Type": "application/json" } : {}) }), [token]);
  const request = useCallback(async (path: string, options: RequestInit = {}): Promise<ApiBody> => {
    const response = await fetch(`${platform.apiUrl}${path}`, { ...options, headers: options.headers ?? headers() });
    const body = (response.status === 204 ? {} : await response.json()) as ApiBody;
    if (!response.ok) throw new Error(Object.values(body.errors ?? {})[0]?.[0] ?? body.message ?? "The request could not be completed.");
    return body;
  }, [headers]);
  const load = useCallback(async () => {
    if (!token) return;
    try {
      const [account, profile, emergency, documents, preferences, notifications, sessions] = await Promise.all([
        request("/auth/me"), request("/modules/profiles/records"), request("/modules/emergency_contacts/records"), request("/modules/travel_documents/records"), request("/modules/passenger_preferences/records"), request("/modules/notification_preferences/records"), request("/account/devices"),
      ]);
      setUser(account as unknown as User);
      setRecords({ profiles: (profile.data as RecordItem[]) ?? [], emergency_contacts: (emergency.data as RecordItem[]) ?? [], travel_documents: (documents.data as RecordItem[]) ?? [], passenger_preferences: (preferences.data as RecordItem[]) ?? [], notification_preferences: (notifications.data as RecordItem[]) ?? [] });
      setDevices((sessions.data as Device[]) ?? []);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load your account."); }
  }, [request, token]);
  useEffect(() => { queueMicrotask(load); }, [load]);

  async function submit(event: FormEvent<HTMLFormElement>, action: () => Promise<unknown>, success: string) {
    event.preventDefault(); setBusy(true); setMessage("");
    try { await action(); setMessage(success); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save changes."); }
    finally { setBusy(false); }
  }
  async function upsert(module: string, values: Record<string, unknown>, existing?: RecordItem) {
    return request(`/modules/${module}/records${existing ? `/${existing.id}` : ""}`, { method: existing ? "PUT" : "POST", body: JSON.stringify(values) });
  }

  if (!token) return <main className="grid min-h-dvh place-items-center bg-[#071b19] px-5 text-white"><section className="max-w-lg rounded-3xl bg-white p-9 text-center text-slate-950"><h1 className="text-3xl font-black">Passenger login required</h1><p className="mt-3 text-slate-500">Sign in to securely manage your personal account.</p><Link href="/login/passenger?next=/account" className="mt-6 inline-flex rounded-full bg-[#ef5b35] px-6 py-3 font-black text-white">Open passenger login</Link></section></main>;
  if (!user) return <main className="grid min-h-dvh place-items-center bg-[#071b19] text-white">Loading your secure account…</main>;
  const preference = records.passenger_preferences?.[0]; const notification = records.notification_preferences?.[0]; const emergency = records.emergency_contacts?.[0];

  return <main className="min-h-dvh bg-[#edf1ef] text-slate-950"><header className="bg-[#0c312d] text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-5 py-8 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#ffce54]">Mufambi passenger</p><h1 className="mt-2 text-4xl font-black">My account</h1><p className="mt-2 text-sm text-emerald-50/70">Everything here is saved to your secure passenger record.</p></div><div className="flex gap-3"><Link href="/home" className="rounded-full border border-white/20 px-5 py-3 text-sm font-bold">Home</Link><button onClick={() => { clearAccessToken(); location.href = "/login/passenger"; }} className="rounded-full bg-white px-5 py-3 text-sm font-black text-[#0c312d]">Sign out</button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 py-7 lg:grid-cols-[19rem_1fr] lg:px-8"><aside className="h-fit rounded-3xl bg-white p-4 shadow-sm"><div className="mb-4 rounded-2xl bg-emerald-50 p-4"><p className="font-black">{user.name}</p><p className="mt-1 truncate text-xs text-emerald-900/60">{user.email}</p><div className="mt-3 flex gap-2 text-[10px] font-black uppercase"><Badge ok={Boolean(user.email_verified_at)} text="Email"/><Badge ok={Boolean(user.phone_verified_at)} text="Phone"/></div></div><nav className="grid gap-1">{tabs.map((item) => <button key={item.key} onClick={() => { setTab(item.key); setMessage(""); }} className={`rounded-2xl px-4 py-3 text-left ${tab === item.key ? "bg-[#0c312d] text-white" : "hover:bg-slate-100"}`}><span className="block text-sm font-black">{item.label}</span><span className={`mt-1 block text-xs ${tab === item.key ? "text-emerald-100/65" : "text-slate-500"}`}>{item.description}</span></button>)}</nav></aside>
      <section className="grid content-start gap-6">{message && <p role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</p>}
        {tab === "profile" && <><Title title="Personal profile" text="Identity, contact details, photograph, language and currency."/><form className={`${card} md:grid-cols-2`} onSubmit={(event) => submit(event, async () => request("/account", { method: "PUT", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }), "Profile saved.")}><Field label="Full name" name="name" value={user.name}/><Field label="Email address" name="email" type="email" value={user.email}/><Field label="Phone number" name="phone" value={user.phone ?? ""}/><Field label="Timezone" name="timezone" value={user.timezone}/><Select label="Preferred language" name="language" value={user.language} options={["en", "sn", "nd", "fr", "pt"]}/><Select label="Preferred currency" name="currency" value={user.currency} options={["USD", "ZAR", "BWP", "ZMW", "MZN"]}/><Save busy={busy}/></form>
          <form className={card} onSubmit={(event) => submit(event, async () => request("/account/profile-photo", { method: "POST", body: new FormData(event.currentTarget), headers: headers(false) }), "Profile photograph updated.")}><h3 className="text-xl font-black">Profile photograph</h3><input required name="photo" type="file" accept="image/jpeg,image/png,image/webp" className={input}/><p className="text-xs text-slate-500">JPG, PNG or WebP, up to 2 MB.</p><Save busy={busy}/></form>
          <form className={`${card} md:grid-cols-2`} onSubmit={(event) => submit(event, async () => { const data = Object.fromEntries(new FormData(event.currentTarget)); return upsert("emergency_contacts", { name: data.name, code: data.relationship, status: "active", data: { phone: data.phone, email: data.email } }, emergency); }, "Emergency contact saved.")}><h3 className="text-xl font-black md:col-span-2">Emergency contact</h3><Field label="Contact name" name="name" value={emergency?.name ?? ""}/><Field label="Relationship" name="relationship" value={emergency?.code ?? ""}/><Field label="Phone" name="phone" value={String(emergency?.data?.phone ?? "")}/><Field label="Email" name="email" type="email" value={String(emergency?.data?.email ?? "")}/><Save busy={busy}/></form></>}
        {tab === "documents" && <><Title title="Identification & passports" text="Sensitive document details are encrypted before database storage."/><form className={`${card} md:grid-cols-2`} onSubmit={(event) => submit(event, async () => { const data = Object.fromEntries(new FormData(event.currentTarget)); return upsert("travel_documents", { name: data.holder_name, code: data.number, status: "active", data: { type: data.type, country: data.country, expires_on: data.expires_on } }); }, "Travel document securely saved.")}><Select label="Document type" name="type" options={["national_id", "passport", "birth_certificate", "residence_permit"]}/><Field label="Holder name" name="holder_name"/><Field label="Document number" name="number"/><Field label="Issuing country" name="country"/><Field label="Expiry date" name="expires_on" type="date"/><Save busy={busy}/></form><List records={records.travel_documents ?? []}/></>}
        {tab === "preferences" && <><Title title="Travel preferences" text="Pre-fill future searches and bookings with your choices."/><PreferenceForm record={preference} busy={busy} submit={submit} upsert={upsert}/></>}
        {tab === "notifications" && <><Title title="Notification preferences" text="Choose how Mufambi contacts you about journeys and offers."/><NotificationForm record={notification} busy={busy} submit={submit} upsert={upsert}/></>}
        {tab === "security" && <Security user={user} devices={devices} busy={busy} submit={submit} request={request} setMessage={setMessage} load={load}/>} 
        {tab === "privacy" && <Privacy busy={busy} submit={submit} request={request}/>} 
      </section></div></main>;
}

type Submit = (event: FormEvent<HTMLFormElement>, action: () => Promise<unknown>, success: string) => Promise<void>;
type Request = (path: string, options?: RequestInit) => Promise<ApiBody>;
type Upsert = (module: string, values: Record<string, unknown>, existing?: RecordItem) => Promise<unknown>;

function PreferenceForm({ record, busy, submit, upsert }: { record?: RecordItem; busy: boolean; submit: Submit; upsert: Upsert }) { const data = record?.data ?? {}; return <form className={`${card} md:grid-cols-2`} onSubmit={(event) => submit(event, async () => upsert("passenger_preferences", { name: "Passenger travel preferences", code: "default", status: "active", data: Object.fromEntries(new FormData(event.currentTarget)) }, record), "Travel preferences saved.")}><Select label="Preferred seat" name="preferred_seat" value={String(data.preferred_seat ?? "window")} options={["window", "aisle", "front", "middle", "rear", "accessible"]}/><Field label="Preferred routes" name="preferred_routes" value={String(data.preferred_routes ?? "")}/><Field label="Preferred operators" name="preferred_operators" value={String(data.preferred_operators ?? "")}/><Field label="Accessibility preferences" name="accessibility" value={String(data.accessibility ?? "")}/><Field label="Mobility or assistance notes" name="assistance_notes" value={String(data.assistance_notes ?? "")}/><Field label="Dietary or medical travel notes" name="travel_notes" value={String(data.travel_notes ?? "")}/><Save busy={busy}/></form>; }
function NotificationForm({ record, busy, submit, upsert }: { record?: RecordItem; busy: boolean; submit: Submit; upsert: Upsert }) { const data = record?.data ?? {}; const keys = ["email", "sms", "push", "booking_updates", "travel_alerts", "promotions"]; return <form className={card} onSubmit={(event) => submit(event, async () => { const form = new FormData(event.currentTarget); return upsert("notification_preferences", { name: "Passenger notifications", code: "default", status: "active", data: Object.fromEntries(keys.map((key) => [key, form.get(key) === "on"])) }, record); }, "Notification preferences saved.")}>{keys.map((key) => <label key={key} className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 font-bold capitalize"><span>{key.replaceAll("_", " ")}</span><input name={key} type="checkbox" defaultChecked={Boolean(data[key] ?? true)} className="size-5 accent-emerald-700"/></label>)}<Save busy={busy}/></form>; }
function Security({ user, devices, busy, submit, request, setMessage, load }: { user: User; devices: Device[]; busy: boolean; submit: Submit; request: Request; setMessage: (value: string) => void; load: () => Promise<void> }) { return <><Title title="Security & active sessions" text="Verification, two-factor authentication and device control."/><div className="grid gap-4 md:grid-cols-3"><Action title="Email verification" status={user.email_verified_at ? "Verified" : "Not verified"} disabled={Boolean(user.email_verified_at)} onClick={async () => setMessage((await request("/email/verification-notification", { method: "POST" })).message)}/><Action title="Phone verification" status={user.phone_verified_at ? "Verified" : "Not verified"} disabled={!user.phone || Boolean(user.phone_verified_at)} onClick={async () => setMessage((await request("/phone/verification-code", { method: "POST" })).message)}/><Action title="Two-factor authentication" status={user.two_factor_confirmed_at ? "Enabled" : "Not enabled"} onClick={async () => { if (user.two_factor_confirmed_at) await request("/two-factor", { method: "DELETE" }); else setMessage(`Authenticator secret: ${(await request("/two-factor/setup", { method: "POST" })).secret}`); await load(); }}/></div>
    {!user.phone_verified_at && user.phone && <CodeForm title="Enter phone verification code" busy={busy} submit={submit} action={(code) => request("/phone/verify", { method: "POST", body: JSON.stringify({ code }) })}/>} {!user.two_factor_confirmed_at && <CodeForm title="Confirm authenticator code" busy={busy} submit={submit} action={(code) => request("/two-factor/confirm", { method: "POST", body: JSON.stringify({ code }) })}/>}<div className={card}><h3 className="text-xl font-black">Active sessions & device history</h3>{devices.map((device) => <div key={device.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div><p className="font-black">{device.name} {device.current && <span className="text-xs text-emerald-700">(this device)</span>}</p><p className="text-xs text-slate-500">Last used {device.last_used_at ? new Date(device.last_used_at).toLocaleString() : "never"}</p></div><button disabled={device.current} onClick={async () => { await request(`/account/devices/${device.id}`, { method: "DELETE" }); await load(); }} className="rounded-xl bg-slate-100 px-4 py-2 text-sm font-black disabled:opacity-40">Sign out</button></div>)}</div></>; }
function Privacy({ busy, submit, request }: { busy: boolean; submit: Submit; request: Request }) { return <><Title title="Privacy & account controls" text="Download your data or control your account lifecycle."/><div className={card}><h3 className="text-xl font-black">Personal-data download</h3><p className="text-sm text-slate-500">Exports profile, preferences, documents, support and travel records.</p><button onClick={async () => { const data = await request("/account/export"); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "mufambi-personal-data.json"; link.click(); URL.revokeObjectURL(url); }} className="w-fit rounded-xl bg-[#0c312d] px-5 py-3 font-black text-white">Download my data</button></div><DangerForm title="Deactivate account" text="Signs out every device. Support can reactivate it." endpoint="/account/deactivation" busy={busy} submit={submit} request={request}/><DangerForm title="Request account deletion" text="Schedules deletion after a 30-day recovery period." endpoint="/account/deletion-requests" busy={busy} submit={submit} request={request}/></>; }
function DangerForm({ title, text, endpoint, busy, submit, request }: { title: string; text: string; endpoint: string; busy: boolean; submit: Submit; request: Request }) { return <form className={card} onSubmit={(event) => submit(event, async () => { const password = new FormData(event.currentTarget).get("password"); await request(endpoint, { method: "POST", body: JSON.stringify({ password }) }); clearAccessToken(); location.href = "/login/passenger"; }, title)}><h3 className="text-xl font-black text-red-700">{title}</h3><p className="text-sm text-slate-500">{text}</p><Field label="Confirm password" name="password" type="password"/><Save busy={busy} label={title} danger/></form>; }
function CodeForm({ title, busy, submit, action }: { title: string; busy: boolean; submit: Submit; action: (code: FormDataEntryValue | null) => Promise<unknown> }) { return <form className={card} onSubmit={(event) => submit(event, () => action(new FormData(event.currentTarget).get("code")), "Verification completed.")}><h3 className="text-xl font-black">{title}</h3><Field label="Six-digit code" name="code"/><Save busy={busy}/></form>; }
function Title({ title, text }: { title: string; text: string }) { return <div className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Passenger accounts</p><h2 className="mt-2 text-3xl font-black">{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p></div>; }
function Field({ label, name, type = "text", value = "" }: { label: string; name: string; type?: string; value?: string }) { return <label className="grid gap-2 text-sm font-bold text-slate-700">{label}<input required className={input} name={name} type={type} defaultValue={value}/></label>; }
function Select({ label, name, options, value }: { label: string; name: string; options: string[]; value?: string }) { return <label className="grid gap-2 text-sm font-bold text-slate-700">{label}<select className={input} name={name} defaultValue={value}>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }
function Save({ busy, label = "Save changes", danger = false }: { busy: boolean; label?: string; danger?: boolean }) { return <button disabled={busy} className={`min-h-12 rounded-xl px-5 font-black text-white disabled:opacity-50 md:w-fit ${danger ? "bg-red-700" : "bg-[#ef5b35]"}`}>{busy ? "Saving…" : label}</button>; }
function List({ records }: { records: RecordItem[] }) { return <div className={card}><h3 className="text-xl font-black">Saved documents</h3>{records.length ? records.map((record) => <div key={record.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-black">{record.name}</p><p className="text-xs text-slate-500">{String(record.data?.type ?? "Document").replaceAll("_", " ")} · {record.code}</p></div>) : <p className="text-sm text-slate-500">No identification or passport details saved yet.</p>}</div>; }
function Action({ title, status, disabled = false, onClick }: { title: string; status: string; disabled?: boolean; onClick: () => Promise<void> }) { return <div className={card}><h3 className="font-black">{title}</h3><p className="text-sm text-slate-500">{status}</p><button disabled={disabled} onClick={() => void onClick()} className="rounded-xl bg-[#0c312d] px-4 py-3 text-sm font-black text-white disabled:bg-emerald-100 disabled:text-emerald-800">{disabled ? status : "Manage"}</button></div>; }
function Badge({ ok, text }: { ok: boolean; text: string }) { return <span className={`rounded-full px-2 py-1 ${ok ? "bg-emerald-700 text-white" : "bg-amber-100 text-amber-900"}`}>{text} {ok ? "verified" : "pending"}</span>; }
