"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { platform } from "@/lib/platform";

type Tracking = { operator: string; route: { origin: string; destination: string }; status: string; location: { latitude: number; longitude: number; recorded_at: string }; distance_remaining_km: number | null; estimated_arrival_minutes: number | null; near_terminal: boolean; unexpected_stop: boolean; route_deviation: boolean; alerts?: string[] };

export default function PublicTrackingPage() {
  const { token } = useParams<{ token: string }>(); const [tracking, setTracking] = useState<Tracking | null>(null); const [error, setError] = useState("");
  useEffect(() => { const load = async () => { try { const response = await fetch(`${platform.apiUrl}/tracking/${token}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Tracking link is unavailable."); setTracking(body); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Tracking is unavailable."); } }; load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, [token]);
  if (!tracking) return <main className="grid min-h-screen place-items-center bg-[#0c312d] p-6 text-white"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-emerald-300">Mufambi live</p><h1 className="mt-3 text-3xl font-black">{error || "Finding the bus…"}</h1></div></main>;
  const mapDelta = 0.04;
  const mapUrl = `https://www.openstreetmap.org/export/embed.html?bbox=${tracking.location.longitude - mapDelta}%2C${tracking.location.latitude - mapDelta}%2C${tracking.location.longitude + mapDelta}%2C${tracking.location.latitude + mapDelta}&layer=mapnik&marker=${tracking.location.latitude}%2C${tracking.location.longitude}`;
  return <main className="min-h-screen bg-[#e8f0ed] px-5 py-8 text-slate-950"><div className="mx-auto max-w-3xl"><header className="rounded-3xl bg-[#0c312d] p-8 text-white"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Live journey · {tracking.operator}</p><h1 className="mt-3 text-4xl font-black">{tracking.route.origin} → {tracking.route.destination}</h1></div><span className="rounded-full bg-emerald-400/20 px-4 py-2 text-sm font-bold capitalize text-emerald-200">{tracking.status}</span></div></header>
    <section className="mt-6 grid gap-5 sm:grid-cols-2"><div className="rounded-3xl bg-white p-7"><p className="text-sm text-slate-500">Estimated arrival</p><p className="mt-2 text-5xl font-black">{tracking.estimated_arrival_minutes ?? "—"}<span className="ml-2 text-lg font-bold text-slate-400">min</span></p></div><div className="rounded-3xl bg-white p-7"><p className="text-sm text-slate-500">Distance remaining</p><p className="mt-2 text-5xl font-black">{tracking.distance_remaining_km ?? "—"}<span className="ml-2 text-lg font-bold text-slate-400">km</span></p></div></section>
    <section className="mt-5 overflow-hidden rounded-3xl bg-white"><iframe title="Live bus location map" src={mapUrl} className="h-80 w-full border-0" loading="lazy" referrerPolicy="no-referrer" /><div className="flex flex-wrap items-center justify-between gap-3 p-5 text-sm"><strong>Latest known bus location</strong><a href={`https://www.openstreetmap.org/?mlat=${tracking.location.latitude}&mlon=${tracking.location.longitude}#map=13/${tracking.location.latitude}/${tracking.location.longitude}`} target="_blank" rel="noreferrer" className="font-bold text-emerald-800 underline">Open larger map</a></div></section>
    <section className="mt-5 rounded-3xl bg-white p-8"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-full bg-emerald-100 text-xl">●</div><div><p className="font-black">{tracking.near_terminal ? "Bus is near a terminal" : "Bus is on its way"}</p><p className="text-sm text-slate-500">Location updated {new Date(tracking.location.recorded_at).toLocaleTimeString()}</p></div></div><div className="my-8 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/3 rounded-full bg-[#ef5b35]" /></div><div className="flex justify-between text-sm font-bold"><span>{tracking.route.origin}</span><span>{tracking.route.destination}</span></div>{(tracking.unexpected_stop || tracking.route_deviation) && <div className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-900">The journey is experiencing an operational exception. The operator has been alerted.</div>}<p className="mt-8 text-xs leading-5 text-slate-400">For driver safety and privacy, public locations are approximate and update every 30 seconds.</p></section>
  </div></main>;
}
