<?php

use App\Http\Controllers\Api\BookingController;
use App\Http\Controllers\Api\GuestTicketController;
use App\Http\Controllers\Api\PaymentWebhookController;
use App\Http\Controllers\Api\TripController;
use App\Http\Controllers\Api\V1\AccountController;
use App\Http\Controllers\Api\V1\AdminCompanyController;
use App\Http\Controllers\Api\V1\AdminDashboardController;
use App\Http\Controllers\Api\V1\AdminOperationsController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BoardingController;
use App\Http\Controllers\Api\V1\BookingCancellationController;
use App\Http\Controllers\Api\V1\BookingCancellationQuoteController;
use App\Http\Controllers\Api\V1\BookingRescheduleController;
use App\Http\Controllers\Api\V1\BookingRescheduleOptionController;
use App\Http\Controllers\Api\V1\BranchController;
use App\Http\Controllers\Api\V1\BusDocumentVerificationController;
use App\Http\Controllers\Api\V1\CompanyApplicationStatusController;
use App\Http\Controllers\Api\V1\CompanyDashboardController;
use App\Http\Controllers\Api\V1\CompanyProfileController;
use App\Http\Controllers\Api\V1\CoreManagementController;
use App\Http\Controllers\Api\V1\EmailVerificationController;
use App\Http\Controllers\Api\V1\FinanceController;
use App\Http\Controllers\Api\V1\FleetController;
use App\Http\Controllers\Api\V1\LoyaltyController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OperatorApplicationController;
use App\Http\Controllers\Api\V1\ParcelController;
use App\Http\Controllers\Api\V1\PassengerBookingController;
use App\Http\Controllers\Api\V1\PasswordResetController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PhoneVerificationController;
use App\Http\Controllers\Api\V1\PlatformResourceController;
use App\Http\Controllers\Api\V1\PlatformStaffController;
use App\Http\Controllers\Api\V1\ReviewController;
use App\Http\Controllers\Api\V1\RoleManagementController;
use App\Http\Controllers\Api\V1\ScheduleController;
use App\Http\Controllers\Api\V1\SeatLayoutController;
use App\Http\Controllers\Api\V1\SocialAuthenticationController;
use App\Http\Controllers\Api\V1\StaffController;
use App\Http\Controllers\Api\V1\StaffInvitationController;
use App\Http\Controllers\Api\V1\SupportController;
use App\Http\Controllers\Api\V1\TicketController;
use App\Http\Controllers\Api\V1\TrackingController;
use App\Http\Controllers\Api\V1\TwoFactorController;
use App\Http\Controllers\Api\V1\WalletController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('/auth/register', [AuthController::class, 'register'])->middleware('throttle:6,1');
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:6,1');
    Route::post('/auth/two-factor-challenge', [TwoFactorController::class, 'challenge'])->middleware('throttle:6,1');
    Route::post('/auth/password/forgot', [PasswordResetController::class, 'requestLink'])->middleware('throttle:6,1');
    Route::post('/auth/password/reset', [PasswordResetController::class, 'reset'])->middleware('throttle:6,1');
    Route::post('/auth/social/{provider}', SocialAuthenticationController::class)->middleware('throttle:12,1');
    Route::post('/staff-invitations/accept', [StaffInvitationController::class, 'accept'])->middleware('throttle:6,1');
    Route::get('/terminals', [TripController::class, 'terminals']);
    Route::get('/trips', [TripController::class, 'index']);
    Route::get('/trips/{trip}', [TripController::class, 'show']);
    Route::post('/trips/{trip}/quote', [BookingController::class, 'quote'])->middleware('throttle:60,1');
    Route::post('/trips/{trip}/seat-locks', [BookingController::class, 'lock'])->middleware('throttle:30,1');
    Route::post('/trips/{trip}/bookings', [BookingController::class, 'store'])->middleware('throttle:20,1');
    Route::get('/guest/bookings/{booking:public_id}/tickets/{ticket:public_id}', GuestTicketController::class)
        ->middleware('throttle:30,1')
        ->name('guest.tickets.pdf');
    Route::post('/guest/bookings/{booking:public_id}/payments', [PaymentController::class, 'store'])
        ->middleware('throttle:10,1')
        ->name('guest.payments.store');
    Route::post('/payments/webhooks/{provider}', PaymentWebhookController::class)->middleware('throttle:120,1')->name('payments.webhook');
    Route::get('/tracking/{token}', [TrackingController::class, 'publicShow'])->middleware('throttle:120,1');
    Route::post('/parcels/quote', [ParcelController::class, 'quote'])->middleware('throttle:60,1');
    Route::get('/parcels/track/{trackingNumber}', [ParcelController::class, 'track'])->middleware('throttle:120,1');

    Route::middleware(['auth:sanctum', 'company.active'])->group(function (): void {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::get('/admin/dashboard', AdminDashboardController::class);
        Route::get('/admin/operations/{resource}', AdminOperationsController::class);
        Route::post('/admin/platform-staff', [PlatformStaffController::class, 'store']);
        Route::patch('/admin/users/{user}/status', [PlatformStaffController::class, 'updateStatus']);
        Route::get('/admin/companies/{company}', [AdminCompanyController::class, 'show']);
        Route::patch('/admin/companies/{company}/status', [AdminCompanyController::class, 'updateStatus']);
        Route::get('/company/dashboard', CompanyDashboardController::class);
        Route::get('/company/profile', [CompanyProfileController::class, 'show']);
        Route::put('/company/profile', [CompanyProfileController::class, 'update']);
        Route::post('/company/profile/logo', [CompanyProfileController::class, 'logo']);
        Route::get('/branches/{branch}/report', [BranchController::class, 'report']);
        Route::apiResource('/branches', BranchController::class);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::put('/account', [AccountController::class, 'update']);
        Route::post('/account/profile-photo', [AccountController::class, 'updateProfilePhoto']);
        Route::get('/account/export', [AccountController::class, 'export'])->middleware('throttle:2,60');
        Route::post('/account/deletion-requests', [AccountController::class, 'requestDeletion'])->middleware('throttle:2,60');
        Route::post('/account/deactivation', [AccountController::class, 'deactivate'])->middleware('throttle:2,60');
        Route::get('/account/devices', [AccountController::class, 'devices']);
        Route::get('/account/login-history', [AccountController::class, 'loginHistory']);
        Route::delete('/account/devices/{tokenId}', [AccountController::class, 'revokeDevice']);
        Route::delete('/account/devices', [AccountController::class, 'revokeDevices']);
        Route::get('/email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed')->name('verification.verify');
        Route::post('/email/verification-notification', [EmailVerificationController::class, 'resend'])->middleware('throttle:6,1');
        Route::post('/phone/verification-code', [PhoneVerificationController::class, 'send'])->middleware('throttle:3,10');
        Route::post('/phone/verify', [PhoneVerificationController::class, 'verify'])->middleware('throttle:6,10');
        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::patch('/notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::get('/notification-preferences', [NotificationController::class, 'preferences']);
        Route::put('/notification-preferences', [NotificationController::class, 'updatePreferences']);
        Route::get('/support-cases', [SupportController::class, 'index']);
        Route::post('/support-cases', [SupportController::class, 'store'])->middleware('throttle:20,1');
        Route::get('/support-cases/{case}', [SupportController::class, 'show']);
        Route::post('/support-cases/{case}/messages', [SupportController::class, 'reply'])->middleware('throttle:30,1');
        Route::patch('/support-cases/{case}/status', [SupportController::class, 'updateStatus']);
        Route::post('/support-cases/{case}/rating', [SupportController::class, 'rate'])->middleware('throttle:10,1');
        Route::post('/two-factor/setup', [TwoFactorController::class, 'setup'])->middleware('throttle:3,10');
        Route::post('/two-factor/confirm', [TwoFactorController::class, 'confirm'])->middleware('throttle:6,10');
        Route::delete('/two-factor', [TwoFactorController::class, 'destroy'])->middleware('throttle:3,10');
        Route::post('/operator-applications', [OperatorApplicationController::class, 'store']);
        Route::post('/operator-applications/{company}/documents', [OperatorApplicationController::class, 'uploadDocument']);
        Route::post('/operator-applications/{company}/submission', [OperatorApplicationController::class, 'submit']);
        Route::post('/operator-applications/{company}/decision', [OperatorApplicationController::class, 'decide']);
        Route::get('/operator-applications/{company}', [CompanyApplicationStatusController::class, 'show']);
        Route::post('/operator-applications/{company}/comments', [CompanyApplicationStatusController::class, 'comment']);
        Route::patch('/operator-applications/{company}/documents/{document}', [CompanyApplicationStatusController::class, 'reviewDocument']);
        Route::apiResource('/schedules', ScheduleController::class);
        Route::get('/bookings/{booking}', [BookingController::class, 'show']);
        Route::get('/bookings', [PassengerBookingController::class, 'index']);
        Route::get('/bookings/{booking}/receipt', [PassengerBookingController::class, 'receipt']);
        Route::post('/bookings/{booking}/review', [ReviewController::class, 'store'])->middleware('throttle:10,1');
        Route::get('/loyalty', [LoyaltyController::class, 'show']);
        Route::put('/loyalty', [LoyaltyController::class, 'update']);
        Route::post('/loyalty/redemptions', [LoyaltyController::class, 'redeem'])->middleware('throttle:10,1');
        Route::post('/loyalty/rewards', [LoyaltyController::class, 'claim'])->middleware('throttle:10,1');
        Route::get('/wallet', [WalletController::class, 'show']);
        Route::post('/wallet/deposits', [WalletController::class, 'deposit'])->middleware('throttle:10,1');
        Route::get('/wallet/statement', [WalletController::class, 'statement']);
        Route::put('/wallet/security', [WalletController::class, 'updateSecurity'])->middleware('throttle:10,1');
        Route::get('/bookings/{booking}/payments', [PaymentController::class, 'index']);
        Route::post('/bookings/{booking}/payments', [PaymentController::class, 'store'])->middleware('throttle:20,1');
        Route::post('/bookings/{booking}/cancellations', BookingCancellationController::class);
        Route::get('/bookings/{booking}/cancellation-quote', BookingCancellationQuoteController::class);
        Route::get('/bookings/{booking}/reschedule-options', BookingRescheduleOptionController::class);
        Route::post('/bookings/{booking}/reschedules', BookingRescheduleController::class);
        Route::get('/tickets/{ticket}/pdf', [TicketController::class, 'pdf']);
        Route::get('/tickets/{ticket}/qr', [TicketController::class, 'qr']);
        Route::get('/trips/{trip}/manifest', [BoardingController::class, 'manifest']);
        Route::post('/boarding/scans', [BoardingController::class, 'scan'])->middleware('throttle:120,1');
        Route::get('/fleet/dashboard', [FleetController::class, 'dashboard']);
        Route::get('/fleet/buses', [FleetController::class, 'buses']);
        Route::post('/fleet/buses', [FleetController::class, 'storeBus']);
        Route::patch('/fleet/buses/{bus}', [FleetController::class, 'updateBus']);
        Route::get('/fleet/buses/{bus}/records', [FleetController::class, 'records']);
        Route::post('/fleet/buses/{bus}/records', [FleetController::class, 'storeRecord']);
        Route::post('/fleet/buses/{bus}/transfer', [FleetController::class, 'transfer']);
        Route::post('/fleet/buses/{bus}/replacement', [FleetController::class, 'replace']);
        Route::get('/fleet/amenities', [FleetController::class, 'amenities']);
        Route::post('/fleet/amenities', [FleetController::class, 'storeAmenity']);
        Route::post('/fleet/buses/{bus}/documents', [FleetController::class, 'storeDocument']);
        Route::patch('/fleet/documents/{document}/verification', BusDocumentVerificationController::class);
        Route::post('/fleet/seat-layouts/{seatLayout}/buses/{bus}', [SeatLayoutController::class, 'apply']);
        Route::apiResource('/fleet/seat-layouts', SeatLayoutController::class);
        Route::post('/fleet/buses/{bus}/maintenance', [FleetController::class, 'scheduleMaintenance']);
        Route::post('/fleet/maintenance/{maintenance}/approve', [FleetController::class, 'approveMaintenance']);
        Route::post('/fleet/maintenance/{maintenance}/start', [FleetController::class, 'startMaintenance']);
        Route::post('/fleet/maintenance/{maintenance}/complete', [FleetController::class, 'completeMaintenance']);
        Route::get('/fleet/maintenance/alerts', [FleetController::class, 'maintenanceAlerts']);
        Route::post('/trips/{trip}/locations', [TrackingController::class, 'update'])->middleware('throttle:180,1');
        Route::get('/trips/{trip}/location-history', [TrackingController::class, 'history']);
        Route::post('/trips/{trip}/tracking-links', [TrackingController::class, 'createLink'])->middleware('throttle:20,1');
        Route::post('/parcels', [ParcelController::class, 'store']);
        Route::get('/parcels/report', [ParcelController::class, 'report']);
        Route::post('/parcels/{parcel}/assign', [ParcelController::class, 'assign']);
        Route::post('/parcels/{parcel}/payment', [ParcelController::class, 'markPaid']);
        Route::post('/parcels/{parcel}/events', [ParcelController::class, 'transition']);
        Route::post('/parcels/{parcel}/collect', [ParcelController::class, 'collect']);
        Route::get('/parcels/{parcel}/label', [ParcelController::class, 'label']);
        Route::get('/staff', [StaffController::class, 'index']);
        Route::post('/staff-invitations', [StaffInvitationController::class, 'store']);
        Route::get('/roles', [RoleManagementController::class, 'index']);
        Route::put('/staff/{user}/role', [RoleManagementController::class, 'assign']);
        Route::patch('/staff/{user}/status', [RoleManagementController::class, 'updateStatus']);
        Route::post('/staff', [StaffController::class, 'store']);
        Route::patch('/staff/{employee}', [StaffController::class, 'update']);
        Route::post('/staff/{employee}/activation', [StaffController::class, 'activate']);
        Route::post('/staff/{employee}/suspension', [StaffController::class, 'suspend']);
        Route::post('/staff/{employee}/assignments', [StaffController::class, 'assign']);
        Route::post('/staff/{employee}/leave', [StaffController::class, 'requestLeave']);
        Route::post('/staff/leave/{leave}/approve', [StaffController::class, 'approveLeave']);
        Route::post('/staff/{employee}/training', [StaffController::class, 'training']);
        Route::post('/staff/{employee}/documents', [StaffController::class, 'storeDocument']);
        Route::post('/staff/{employee}/reports', [StaffController::class, 'storeReport']);
        Route::post('/staff/{employee}/working-hours', [StaffController::class, 'storeWorkingHours']);
        Route::get('/staff-alerts', [StaffController::class, 'alerts']);
        Route::get('/finance/dashboard', [FinanceController::class, 'dashboard']);
        Route::post('/finance/settlements', [FinanceController::class, 'createSettlement']);
        Route::post('/finance/settlements/{settlement}/approve', [FinanceController::class, 'approve']);
        Route::post('/finance/settlements/{settlement}/pay', [FinanceController::class, 'pay']);
        Route::post('/finance/reconciliations', [FinanceController::class, 'reconcile']);
        Route::apiResource('/modules/{module}/records', PlatformResourceController::class)->parameters(['records' => 'id']);
        Route::apiResource('/management/{resource}/records', CoreManagementController::class)->parameters(['records' => 'id']);
    });
});
