"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { platform } from "@/lib/platform";
import { readAccessToken } from "@/lib/auth-token";

type Dashboard = { branches: number; staff: number; buses: { total: number; available: number; under_maintenance: number }; scheduled_trips: number; active_trips: number; today_bookings: number; today_revenue: number; seat_occupancy_percent: number; delayed_trips: number; pending_refunds: number; wallet_balance: number; next_settlement: { code: string; net_amount: string; currency: string } | null; recent_activities: Array<{ id: number; name: string; created_at: string }> };

const workspaces = [["/operator/fleet", "Fleet & maintenance"], ["/operator/staff", "Staff & roster"], ["/operator/finance", "Finance & settlements"], ["/operator/manage", "Routes, schedules, fares & policies"], ["/terminal", "Boarding terminal"], ["/driver/operations", "Driver & conductor"]] as const;

export default function OperatorPage() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${platform.apiUrl}/company/dashboard`, { headers: { Accept: "application/json", Authorization: `Bearer ${readAccessToken()}` } }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Company access is required."); setDashboard(body); }).catch((error) => setMessage(error.message)); }, []);
  const metrics = [["Branches", dashboard?.branches], ["Total buses", dashboard?.buses.total], ["Available buses", dashboard?.buses.available], ["Active trips", dashboard?.active_trips], ["Today’s bookings", dashboard?.today_bookings], ["Today’s revenue", `$${Number(dashboard?.today_revenue ?? 0).toFixed(2)}`], ["Seat occupancy", `${dashboard?.seat_occupancy_percent ?? 0}%`], ["Delayed trips", dashboard?.delayed_trips], ["Pending refunds", dashboard?.pending_refunds]];
  return <main className="min-h-screen bg-[#edf1ef] text-slate-950"><header className="bg-[#0c312d] px-5 py-12 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.24em] text-[#ffce54]">Private company workspace</p><h1 className="mt-3 text-5xl font-black">Company dashboard</h1><p className="mt-4 max-w-2xl text-emerald-50/70">Every figure is automatically filtered by the authenticated user’s company.</p></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">{message && <p className="mb-5 rounded-2xl bg-red-50 p-4 text-sm text-red-900">{message}</p>}<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label, value]) => <article key={label} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 text-4xl font-black">{value ?? 0}</p></article>)}</section><section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><div className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Company operations</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{workspaces.map(([href, label]) => <Link key={href} href={href} className="rounded-2xl border border-slate-200 p-5 font-black transition hover:border-emerald-700 hover:bg-emerald-50">{label}</Link>)}</div>{dashboard?.next_settlement && <div className="mt-5 rounded-2xl bg-amber-50 p-5"><p className="text-xs font-bold uppercase text-amber-800">Next settlement</p><p className="mt-2 text-xl font-black">{dashboard.next_settlement.currency} {dashboard.next_settlement.net_amount}</p></div>}</div><div className="rounded-3xl bg-slate-950 p-6 text-white"><h2 className="text-2xl font-black">Recent company activity</h2><div className="mt-5 grid gap-4">{dashboard?.recent_activities.map((activity) => <article key={activity.id} className="border-b border-white/10 pb-4"><p className="text-sm font-bold">{activity.name}</p><p className="mt-1 text-xs text-slate-400">{new Date(activity.created_at).toLocaleString()}</p></article>)}{!dashboard?.recent_activities.length && <p className="text-sm text-slate-400">No recent company activity.</p>}</div></div></section></div></main>;
}
