"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { platform } from "@/lib/platform";

type Bus = { id: number; registration_number: string; model: string; class: string; status: string; seat_capacity: number; seats_count: number; mileage_km: number; manufacturing_year: number | null; documents: { id: number; document_type: string; expires_on: string | null }[] };
type Dashboard = { fleet_total: number; by_status: Record<string, number>; expiring_documents: unknown[]; overdue_maintenance: unknown[] };

export default function FleetPage() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem("mufambi-token") ?? ""); const [buses, setBuses] = useState<Bus[]>([]); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [selected, setSelected] = useState<Bus | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const headers = useCallback(() => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${token}` }), [token]);
  const load = useCallback(async () => { if (!token) return; setLoading(true); try { const [fleetResponse, dashboardResponse] = await Promise.all([fetch(`${platform.apiUrl}/fleet/buses`, { headers: headers() }), fetch(`${platform.apiUrl}/fleet/dashboard`, { headers: headers() })]); const fleet = await fleetResponse.json(); const summary = await dashboardResponse.json(); if (!fleetResponse.ok) throw new Error(fleet.message ?? "Unable to load fleet."); setBuses(fleet.data ?? []); setDashboard(summary); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load fleet."); } finally { setLoading(false); } }, [headers, token]);
  useEffect(() => { if (token) queueMicrotask(load); }, [load, token]);
  function saveToken(value: string) { setToken(value); localStorage.setItem("mufambi-token", value); }

  async function schedule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); setLoading(true); const response = await fetch(`${platform.apiUrl}/fleet/buses/${selected.id}/maintenance`, { method: "POST", headers: headers(), body: JSON.stringify({ maintenance_type: form.get("type"), scheduled_at: form.get("date"), odometer_km: Number(form.get("odometer")), notes: form.get("notes") }) }); const body = await response.json(); setMessage(response.ok ? `Maintenance scheduled for ${selected.registration_number}.` : body.message ?? "Could not schedule maintenance."); setSelected(null); await load(); setLoading(false); }

  return <main className="min-h-screen bg-[#eef2f1] text-slate-950"><header className="bg-[#0c312d] px-6 py-6 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-300">Mufambi Operator</p><h1 className="mt-1 text-3xl font-black">Fleet control</h1></div><label className="text-xs text-emerald-100">Access token<input type="password" value={token} onChange={(e) => saveToken(e.target.value)} className="ml-3 rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-white outline-none" /></label></div></header>
    <div className="mx-auto max-w-7xl px-6 py-8"><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total fleet" value={dashboard?.fleet_total ?? 0} /><Metric label="Available" value={dashboard?.by_status.available ?? 0} /><Metric label="Documents expiring" value={dashboard?.expiring_documents.length ?? 0} alert /><Metric label="Maintenance overdue" value={dashboard?.overdue_maintenance.length ?? 0} alert /></section>
      {message && <div className="mt-6 rounded-2xl border border-emerald-200 bg-white p-4 text-sm">{message}</div>}
      <section className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h2 className="text-xl font-black">Vehicles</h2><p className="text-sm text-slate-500">Live operational status and compliance</p></div><button onClick={load} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">{loading ? "Loading…" : "Refresh"}</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Vehicle</th><th className="p-4">Class</th><th className="p-4">Mileage</th><th className="p-4">Compliance</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{buses.map((bus) => <tr key={bus.id} className="border-t border-slate-100"><td className="p-4"><strong>{bus.registration_number}</strong><span className="block text-xs text-slate-500">{bus.model} {bus.manufacturing_year ? `· ${bus.manufacturing_year}` : ""}</span></td><td className="p-4 capitalize">{bus.class}<span className="block text-xs text-slate-500">{bus.seats_count || bus.seat_capacity} seats</span></td><td className="p-4">{Number(bus.mileage_km).toLocaleString()} km</td><td className="p-4">{bus.documents.length} documents</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${bus.status === "available" ? "bg-emerald-50 text-emerald-800" : bus.status === "under_maintenance" ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-700"}`}>{bus.status.replaceAll("_", " ")}</span></td><td className="p-4"><button onClick={() => setSelected(bus)} className="font-bold text-emerald-800">Schedule service</button></td></tr>)}</tbody></table>{!buses.length && <p className="p-12 text-center text-slate-500">Add an access token to load your company fleet.</p>}</div></section>
      {selected && <div className="fixed inset-0 grid place-items-center bg-slate-950/60 p-5"><form onSubmit={schedule} className="w-full max-w-md rounded-3xl bg-white p-7"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{selected.registration_number}</p><h2 className="mt-2 text-2xl font-black">Schedule maintenance</h2><div className="mt-6 grid gap-4"><label className="text-sm font-bold">Maintenance type<select name="type" className="input mt-2"><option value="service">Service</option><option value="preventive">Preventive</option><option value="repair">Repair</option><option value="inspection">Inspection</option><option value="tyres">Tyres</option></select></label><label className="text-sm font-bold">Date and time<input required name="date" type="datetime-local" className="input mt-2" /></label><label className="text-sm font-bold">Odometer<input required name="odometer" type="number" min={selected.mileage_km} defaultValue={selected.mileage_km} className="input mt-2" /></label><label className="text-sm font-bold">Notes<textarea name="notes" className="input mt-2 min-h-24" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setSelected(null)} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Cancel</button><button className="rounded-xl bg-[#ef5b35] px-5 py-3 font-bold text-white">Schedule</button></div></form></div>}
    </div></main>;
}

function Metric({ label, value, alert = false }: { label: string; value: number; alert?: boolean }) { return <div className={`rounded-3xl p-6 ${alert && value ? "bg-amber-100 text-amber-950" : "bg-white"}`}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-4xl font-black">{value}</p></div>; }
