"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { platform } from "@/lib/platform";

type Employee = { id: number; employee_number: string; name: string; staff_type: string; availability_status: string; driver_licence_expires_on: string | null; assignments: { id: number; duty_role: string; assigned_from: string; assigned_until: string }[] };

export default function StaffPage() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem("mufambi-token") ?? ""); const [staff, setStaff] = useState<Employee[]>([]); const [message, setMessage] = useState(""); const [showForm, setShowForm] = useState(false); const [type, setType] = useState("driver");
  const headers = useCallback(() => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${token}` }), [token]);
  const load = useCallback(async () => { if (!token) return; const response = await fetch(`${platform.apiUrl}/staff`, { headers: headers() }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Unable to load staff."); setStaff(body.data ?? []); }, [headers, token]);
  useEffect(() => { queueMicrotask(load); }, [load]);
  function saveToken(value: string) { setToken(value); localStorage.setItem("mufambi-token", value); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(`${platform.apiUrl}/staff`, { method: "POST", headers: headers(), body: JSON.stringify({ ...values, staff_type: type }) }); const body = await response.json(); if (!response.ok) return setMessage(errorMessage(body)); setMessage(`${body.name} was added to the roster.`); setShowForm(false); await load(); }
  return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="bg-[#0c312d] px-6 py-7 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Mufambi Operator</p><h1 className="mt-2 text-3xl font-black">People & roster</h1></div><label className="text-xs text-emerald-100">Access token<input type="password" value={token} onChange={(e) => saveToken(e.target.value)} className="ml-3 rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-white" /></label></div></header><div className="mx-auto max-w-7xl px-6 py-8">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Transport staff</h2><p className="text-sm text-slate-500">Licences, availability and upcoming duties</p></div><button onClick={() => setShowForm(true)} className="rounded-xl bg-[#ef5b35] px-5 py-3 font-bold text-white">Add employee</button></div>{message && <p className="mt-5 rounded-2xl bg-white p-4 text-sm">{message}</p>}
    <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{staff.map((employee) => <article key={employee.id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{employee.employee_number}</p><h3 className="mt-2 text-xl font-black">{employee.name}</h3><p className="mt-1 text-sm capitalize text-slate-500">{employee.staff_type.replaceAll("_", " ")}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-800">{employee.availability_status}</span></div>{employee.driver_licence_expires_on && <p className="mt-5 rounded-xl bg-slate-50 p-3 text-xs">Licence expires <strong>{new Date(employee.driver_licence_expires_on).toLocaleDateString()}</strong></p>}<div className="mt-5 border-t border-slate-100 pt-4"><p className="text-xs font-bold uppercase text-slate-400">Upcoming assignments</p>{employee.assignments.length ? employee.assignments.map((assignment) => <p key={assignment.id} className="mt-2 text-sm"><strong className="capitalize">{assignment.duty_role}</strong> · {new Date(assignment.assigned_from).toLocaleString()}</p>) : <p className="mt-2 text-sm text-slate-400">No upcoming duties</p>}</div></article>)}{!staff.length && <div className="rounded-3xl border border-dashed border-slate-300 p-12 text-center text-slate-500 md:col-span-2 xl:col-span-3">Add an access token to load the company roster.</div>}</section>
    {showForm && <div className="fixed inset-0 grid place-items-center overflow-y-auto bg-slate-950/60 p-5"><form onSubmit={create} className="my-8 w-full max-w-lg rounded-3xl bg-white p-7"><h2 className="text-2xl font-black">Add employee</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input required name="employee_number" placeholder="Employee number" className="input" /><input required name="name" placeholder="Full name" className="input" /><select value={type} onChange={(e) => setType(e.target.value)} className="input sm:col-span-2"><option value="driver">Driver</option><option value="conductor">Conductor</option><option value="terminal_officer">Terminal officer</option><option value="booking_clerk">Booking clerk</option><option value="maintenance_officer">Maintenance officer</option><option value="manager">Manager</option></select>{type === "driver" && <><input required name="driver_licence_number" placeholder="Licence number" className="input" /><input required name="driver_licence_class" placeholder="Licence class" className="input" /><label className="text-xs font-bold uppercase text-slate-500 sm:col-span-2">Licence expiry<input required name="driver_licence_expires_on" type="date" className="input mt-2" /></label></>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowForm(false)} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Cancel</button><button className="rounded-xl bg-[#0c312d] px-5 py-3 font-bold text-white">Add employee</button></div></form></div>}
  </div></main>;
}

function errorMessage(body: { message?: string; errors?: Record<string, string[]> }) { return Object.values(body.errors ?? {})[0]?.[0] ?? body.message ?? "Request failed."; }
