"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { readAccessToken } from "@/lib/auth-token";
import { platform } from "@/lib/platform";

type RecordValue = string | number | null | { name?: string; registration_number?: string };
type MonitorRecord = { id: number; name?: string; email?: string; role?: string; status?: string; company?: { name?: string }; registration_number?: string; model?: string; reference?: string; contact_name?: string; provider?: string; provider_reference?: string; amount?: number; total?: number; currency?: string; departs_at?: string; created_at: string; [key: string]: RecordValue | undefined };
const resources = ["passengers", "platform-staff", "buses", "trips", "bookings", "payments"] as const;

export default function AdminMonitorPage() {
  const [resource, setResource] = useState<(typeof resources)[number]>("passengers");
  const [records, setRecords] = useState<MonitorRecord[]>([]); const [search, setSearch] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [showCreate, setShowCreate] = useState(false);
  const headers = useCallback(() => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${readAccessToken()}` }), []);
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams({ search }); const response = await fetch(`${platform.apiUrl}/admin/operations/${resource}?${query}`, { headers: headers() }); const body = await response.json(); setLoading(false); if (!response.ok) { setRecords([]); return setMessage(body.message ?? "Unable to load records."); } setRecords(body.data ?? []); setMessage(""); }, [headers, resource, search]);
  useEffect(() => { queueMicrotask(load); }, [load]);
  async function changeStatus(record: MonitorRecord) { const status = record.status === "suspended" ? "active" : "suspended"; const reason = window.prompt(`Reason to mark this account ${status}?`); if (!reason) return; const response = await fetch(`${platform.apiUrl}/admin/users/${record.id}/status`, { method: "PATCH", headers: headers(), body: JSON.stringify({ status, reason }) }); const body = await response.json(); setMessage(response.ok ? `${record.name ?? "Account"} is now ${status}.` : body.message ?? "Status change failed."); if (response.ok) await load(); }
  async function createStaff(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`${platform.apiUrl}/admin/platform-staff`, { method: "POST", headers: headers(), body: JSON.stringify(Object.fromEntries(form)) }); const body = await response.json(); setMessage(response.ok ? "Platform staff account created." : body.message ?? "Account creation failed."); if (response.ok) { event.currentTarget.reset(); setResource("platform-staff"); setShowCreate(false); await load(); } }
  return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="bg-[#0c312d] px-5 py-10 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.22em] text-[#ffce54]">Read-only global operations</p><h1 className="mt-2 text-4xl font-black">Platform monitoring</h1><p className="mt-3 text-emerald-50/70">Monitor passengers, platform staff, every operator bus, trip, booking and payment without crossing company edit boundaries.</p></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">
    <div className="flex flex-wrap gap-2">{resources.map((item) => <button key={item} onClick={() => setResource(item)} className={`rounded-full px-4 py-2 text-sm font-black capitalize ${resource === item ? "bg-emerald-800 text-white" : "bg-white"}`}>{item.replace("-", " ")}</button>)}</div>
    <div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search visible records" className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-white px-4 py-3" />{resource === "platform-staff" && <button onClick={() => setShowCreate((value) => !value)} className="rounded-2xl bg-[#ef5b35] px-5 py-3 font-black text-white">Add platform staff</button>}</div>
    {showCreate && <form onSubmit={createStaff} className="mt-5 grid gap-3 rounded-3xl bg-white p-5 md:grid-cols-2"><input required name="name" placeholder="Full name" className="rounded-xl border p-3"/><input required type="email" name="email" placeholder="Email" className="rounded-xl border p-3"/><input required minLength={12} type="password" name="password" placeholder="Temporary password (12+ characters)" className="rounded-xl border p-3"/><select name="role" className="rounded-xl border p-3"><option value="operator_approval_officer">Operator approval officer</option><option value="platform_finance_officer">Platform finance officer</option><option value="customer_support_officer">Customer support officer</option><option value="marketing_manager">Marketing manager</option><option value="security_administrator">Security administrator</option><option value="system_auditor">System auditor</option></select><button className="rounded-xl bg-emerald-800 p-3 font-black text-white md:col-span-2">Create protected account</button></form>}
    {message && <p role="alert" className="mt-5 rounded-2xl bg-white p-4 text-sm">{message}</p>}
    <div className="mt-5 overflow-x-auto rounded-3xl bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="p-4">Record</th><th className="p-4">Company / role</th><th className="p-4">Reference</th><th className="p-4">Value</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4">Action</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-b border-slate-100"><td className="p-4 font-bold">{record.name ?? record.contact_name ?? record.model ?? record.provider ?? `#${record.id}`}<span className="block text-xs font-normal text-slate-500">{record.email}</span></td><td className="p-4">{record.company?.name ?? record.role ?? "Platform"}</td><td className="p-4">{record.reference ?? record.registration_number ?? record.provider_reference ?? "—"}</td><td className="p-4">{record.amount ?? record.total ?? "—"} {record.currency}</td><td className="p-4 capitalize">{record.status ?? "—"}</td><td className="p-4">{new Date(record.created_at).toLocaleString()}</td><td className="p-4">{(resource === "passengers" || resource === "platform-staff") && record.role !== "super_administrator" ? <button onClick={() => changeStatus(record)} className="rounded-lg border px-3 py-2 font-bold">{record.status === "suspended" ? "Reactivate" : "Suspend"}</button> : "View only"}</td></tr>)}</tbody></table>{!records.length && <p className="p-10 text-center text-slate-500">{loading ? "Loading records…" : "No matching records."}</p>}</div>
  </div></main>;
}
