"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { platform } from "@/lib/platform";

type Wallet = { id: number; wallet_type: string; currency: string; balance: string; available_balance: string; held_balance: string };
type Dashboard = { wallets: Wallet[]; gross_booking_value: number; platform_fees: number; operator_revenue: number; unsettled_amount: number; pending_settlements: number };

export default function FinancePage() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem("mufambi-token") ?? ""); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [message, setMessage] = useState(""); const [showSettlement, setShowSettlement] = useState(false);
  const headers = useCallback(() => ({ Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${token}` }), [token]);
  const load = useCallback(async () => { if (!token) return; const response = await fetch(`${platform.apiUrl}/finance/dashboard`, { headers: headers() }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Unable to load finance data."); setDashboard(body); }, [headers, token]);
  useEffect(() => { queueMicrotask(load); }, [load]);
  function saveToken(value: string) { setToken(value); localStorage.setItem("mufambi-token", value); }
  async function settle(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(`${platform.apiUrl}/finance/settlements`, { method: "POST", headers: headers(), body: JSON.stringify(values) }); const body = await response.json(); if (!response.ok) return setMessage(errorMessage(body)); setMessage(`Settlement ${body.code} prepared for ${body.currency} ${body.net_amount}. A different finance user must approve it.`); setShowSettlement(false); await load(); }
  return <main className="min-h-screen bg-[#f3f5f4] text-slate-950"><header className="bg-[#0c312d] px-6 py-7 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Mufambi Operator</p><h1 className="mt-2 text-3xl font-black">Finance & settlements</h1></div><label className="text-xs text-emerald-100">Access token<input type="password" value={token} onChange={(e) => saveToken(e.target.value)} className="ml-3 rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-white" /></label></div></header><div className="mx-auto max-w-7xl px-6 py-8">
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Gross bookings" value={dashboard?.gross_booking_value} /><Metric label="Operator revenue" value={dashboard?.operator_revenue} /><Metric label="Platform fees" value={dashboard?.platform_fees} /><Metric label="Awaiting settlement" value={dashboard?.unsettled_amount} alert /><Metric label="Pending batches" value={dashboard?.pending_settlements} plain /></section>
    {message && <p className="mt-6 rounded-2xl border border-emerald-100 bg-white p-4 text-sm">{message}</p>}
    <section className="mt-8 rounded-3xl bg-white p-7 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-black">Wallet balances</h2><p className="text-sm text-slate-500">Posted, available and held operator funds</p></div><button onClick={() => setShowSettlement(true)} className="rounded-xl bg-[#ef5b35] px-5 py-3 font-bold text-white">Prepare settlement</button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{dashboard?.wallets.map((wallet) => <article key={wallet.id} className="rounded-2xl bg-slate-50 p-6"><div className="flex justify-between"><p className="font-bold capitalize">{wallet.wallet_type} wallet</p><span className="text-sm font-bold">{wallet.currency}</span></div><p className="mt-4 text-4xl font-black">{wallet.currency} {wallet.balance}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><p>Available <strong className="block">{wallet.available_balance}</strong></p><p>Held <strong className="block">{wallet.held_balance}</strong></p></div></article>)}{!dashboard?.wallets.length && <p className="text-sm text-slate-500">Wallets appear after the first confirmed payment.</p>}</div></section>
    <section className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-black text-amber-950">Payment control</h2><p className="mt-2 text-sm leading-6 text-amber-900">One finance user prepares a settlement, a second approves it, and a third releases payment. This separation prevents unauthorized payouts.</p></section>
    {showSettlement && <div className="fixed inset-0 grid place-items-center bg-slate-950/60 p-5"><form onSubmit={settle} className="w-full max-w-md rounded-3xl bg-white p-7"><h2 className="text-2xl font-black">Prepare settlement</h2><div className="mt-6 grid gap-4"><label className="text-sm font-bold">Period start<input required name="period_start" type="date" className="input mt-2" /></label><label className="text-sm font-bold">Period end<input required name="period_end" type="date" className="input mt-2" /></label><label className="text-sm font-bold">Currency<select name="currency" className="input mt-2"><option>USD</option><option>ZAR</option><option>ZWG</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowSettlement(false)} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Cancel</button><button className="rounded-xl bg-[#0c312d] px-5 py-3 font-bold text-white">Prepare</button></div></form></div>}
  </div></main>;
}

function Metric({ label, value = 0, alert = false, plain = false }: { label: string; value?: number; alert?: boolean; plain?: boolean }) { return <div className={`rounded-3xl p-5 ${alert && value ? "bg-amber-100" : "bg-white"}`}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{plain ? value : `$${Number(value).toFixed(2)}`}</p></div>; }
function errorMessage(body: { message?: string; errors?: Record<string, string[]> }) { return Object.values(body.errors ?? {})[0]?.[0] ?? body.message ?? "Request failed."; }
