"use client";

import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { platform } from "@/lib/platform";

type Stop = { id: number; name: string; starts_at: string | null; data: { terminal?: string } | null };
type Seat = { id: number; number: string; position: string; availability: "available" | "occupied"; accessible: boolean };
type Trip = { id: number; departs_at: string; arrives_at: string; duration_minutes: number; base_fare: string; currency: string; available_seats: number; operator_rating: number; luggage_allowance: string; refund_policy: { label: string }; cancellation_policy: Array<{ minimum_hours: number; refund_percent: number }>; intermediate_stops: Stop[]; company: { name: string }; route: { origin: { name: string; city: string }; destination: { name: string; city: string } }; bus: { model: string; class: string; images: string[] | null; amenities: string[] | null; seat_layout: { columns: number }; seats: Seat[] } };

export default function TripDetailsPage() {
  const { id } = useParams<{ id: string }>();
  const [trip, setTrip] = useState<Trip | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${platform.apiUrl}/trips/${id}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Trip not found."); setTrip(body); }).catch((error) => setMessage(error instanceof Error ? error.message : "Trip not found.")); }, [id]);
  if (!trip) return <main className="grid min-h-dvh place-items-center bg-[#0c312d] px-5 text-white">{message || "Loading trip details…"}</main>;

  return <main className="min-h-dvh bg-[#edf1ef] text-slate-950"><header className="bg-[#0c312d] px-5 py-12 text-white lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/compare" className="text-sm font-bold text-[#ffce54]">← Back to results</Link><p className="mt-8 text-xs font-black uppercase tracking-[.22em] text-[#ffce54]">{trip.company.name}</p><h1 className="mt-3 text-5xl font-black">{trip.route.origin.city} → {trip.route.destination.city}</h1><p className="mt-4 text-emerald-50/70">{new Date(trip.departs_at).toLocaleString()} · {trip.duration_minutes} minutes · ★ {trip.operator_rating.toFixed(1)}</p></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><section className="grid content-start gap-6">
      {trip.bus.images?.length ? <div className="grid gap-3 sm:grid-cols-2">{trip.bus.images.map((image) => <Image unoptimized key={image} src={image} alt={`${trip.company.name} ${trip.bus.model}`} width={800} height={512} className="h-64 w-full rounded-3xl object-cover"/>)}</div> : <div className="grid h-64 place-items-center rounded-3xl bg-[#dce5df] text-slate-500">No bus images supplied</div>}
      <article className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Journey details</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact label="Bus" value={`${trip.bus.model} · ${trip.bus.class}`}/><Fact label="Fare" value={`${trip.currency} ${trip.base_fare}`}/><Fact label="Boarding" value={`${trip.route.origin.name}, ${trip.route.origin.city}`}/><Fact label="Drop-off" value={`${trip.route.destination.name}, ${trip.route.destination.city}`}/><Fact label="Departure" value={new Date(trip.departs_at).toLocaleString()}/><Fact label="Arrival" value={new Date(trip.arrives_at).toLocaleString()}/><Fact label="Luggage" value={trip.luggage_allowance}/><Fact label="Refunds" value={trip.refund_policy.label}/></dl></article>
      <article className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Stops and policies</h2><div className="mt-5 grid gap-3">{trip.intermediate_stops.length ? trip.intermediate_stops.map((stop) => <div key={stop.id} className="rounded-2xl bg-slate-50 p-4"><strong>{stop.name}</strong><p className="text-sm text-slate-500">{stop.data?.terminal ?? "Intermediate stop"}{stop.starts_at ? ` · ${new Date(stop.starts_at).toLocaleString()}` : ""}</p></div>) : <p className="text-sm text-slate-500">This is listed as a direct service.</p>}</div><div className="mt-5 text-sm text-slate-600">{trip.cancellation_policy.length ? trip.cancellation_policy.map((rule) => <p key={rule.minimum_hours}>{rule.refund_percent}% refund when cancelled at least {rule.minimum_hours} hours before departure.</p>) : <p>Contact the operator for cancellation conditions.</p>}</div></article>
    </section><aside className="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Seat layout</h2><p className="mt-2 text-sm text-slate-500">Available {trip.available_seats} · Window W · Aisle A · Accessible ♿</p><div className="mt-5 grid gap-3 rounded-2xl bg-slate-100 p-4" style={{ gridTemplateColumns: `repeat(${trip.bus.seat_layout.columns}, minmax(0, 1fr))` }}>{trip.bus.seats.map((seat) => <div key={seat.id} title={`${seat.position} seat`} className={`rounded-xl border p-3 text-center text-sm font-black ${seat.availability === "occupied" ? "border-slate-300 bg-slate-300 text-slate-500" : "border-emerald-700 bg-white text-emerald-900"}`}>{seat.number}<span className="block text-[10px] uppercase">{seat.position === "window" ? "W" : seat.position === "aisle" ? "A" : "—"}{seat.accessible ? " ♿" : ""}</span></div>)}</div><div className="mt-5 flex flex-wrap gap-2">{trip.bus.amenities?.map((amenity) => <span key={amenity} className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-900">{amenity.replaceAll("_", " ")}</span>)}</div><Link href="/book" className="mt-6 block rounded-xl bg-[#ef5b35] px-5 py-4 text-center font-black text-white">Select seats and book</Link></aside></div>
  </main>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>; }
