"use client";

import { FormEvent, useState } from "react";
import { platform } from "@/lib/platform";

type Event = { type: string; recorded_at: string }; type Tracking = { tracking_number: string; status: string; route: { origin: string; destination: string }; events: Event[] };

export default function ParcelsPage() {
  const [trackingNumber, setTrackingNumber] = useState(""); const [tracking, setTracking] = useState<Tracking | null>(null); const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [created, setCreated] = useState<{ tracking: string; code: string } | null>(null);
  async function track(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch(`${platform.apiUrl}/parcels/track/${trackingNumber.trim()}`); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Parcel not found."); setTracking(body); }
  async function book(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); const response = await fetch(`${platform.apiUrl}/parcels`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...payload, route_id: Number(payload.route_id), weight_kg: Number(payload.weight_kg), length_cm: Number(payload.length_cm), width_cm: Number(payload.width_cm), height_cm: Number(payload.height_cm), prohibited_items_declared: true }) }); const body = await response.json(); if (!response.ok) return setMessage(errorMessage(body)); setCreated({ tracking: body.parcel.tracking_number, code: body.collection_code }); setMessage(""); }
  return <main className="min-h-screen bg-[#f5f3ee] text-slate-950"><header className="bg-[#0c312d] px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.22em] text-[#ffce54]">Mufambi parcels</p><h1 className="mt-3 max-w-2xl text-5xl font-black">Send it safely. Follow every handover.</h1><p className="mt-4 text-emerald-50/70">Bus-powered delivery with verified collection across the network.</p></div></header><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-2">
    <section className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Track a parcel</h2><form onSubmit={track} className="mt-5 flex gap-3"><input required value={trackingNumber} onChange={(e) => setTrackingNumber(e.target.value.toUpperCase())} placeholder="Tracking number" className="input" /><button className="rounded-xl bg-[#ef5b35] px-6 font-bold text-white">Track</button></form>{tracking && <div className="mt-7"><div className="rounded-2xl bg-emerald-50 p-5"><p className="text-xs font-bold uppercase text-emerald-700">{tracking.status.replaceAll("_", " ")}</p><p className="mt-2 text-lg font-black">{tracking.route.origin} → {tracking.route.destination}</p></div><ol className="mt-6 border-l-2 border-emerald-200 pl-6">{[...tracking.events].reverse().map((item, index) => <li key={`${item.type}-${index}`} className="relative pb-6 before:absolute before:-left-[31px] before:top-1 before:size-3 before:rounded-full before:bg-emerald-600"><p className="font-bold capitalize">{item.type.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{new Date(item.recorded_at).toLocaleString()}</p></li>)}</ol></div>}{message && <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{message}</p>}</section>
    <section className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Parcel desk booking</h2><p className="mt-1 text-sm text-slate-500">For authenticated agents and operator staff.</p><label className="mt-5 block text-xs font-bold uppercase text-slate-500">Access token<input type="password" value={token} onChange={(e) => setToken(e.target.value)} className="input mt-2" /></label>{created ? <div className="mt-6 rounded-2xl bg-[#0c312d] p-6 text-white"><p className="text-sm text-emerald-300">Parcel booked</p><p className="mt-2 text-2xl font-black">{created.tracking}</p><p className="mt-4 text-sm">Collection code: <strong className="text-xl text-[#ffce54]">{created.code}</strong></p><p className="mt-3 text-xs text-white/60">Give this code only to the intended receiver.</p><button onClick={() => setCreated(null)} className="mt-5 rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-950">Book another</button></div> : <form onSubmit={book} className="mt-5 grid gap-3 sm:grid-cols-2"><input required name="route_id" inputMode="numeric" placeholder="Route ID" className="input sm:col-span-2" /><input required name="sender_name" placeholder="Sender name" className="input" /><input required name="sender_phone" placeholder="Sender phone" className="input" /><input required name="receiver_name" placeholder="Receiver name" className="input" /><input required name="receiver_phone" placeholder="Receiver phone" className="input" /><textarea required name="description" placeholder="Parcel description" className="input min-h-24 sm:col-span-2" /><input required name="weight_kg" type="number" step="0.01" min="0.01" placeholder="Weight kg" className="input" /><input required name="length_cm" type="number" step="0.1" min="0.1" placeholder="Length cm" className="input" /><input required name="width_cm" type="number" step="0.1" min="0.1" placeholder="Width cm" className="input" /><input required name="height_cm" type="number" step="0.1" min="0.1" placeholder="Height cm" className="input" /><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:col-span-2"><input required type="checkbox" className="mt-1" />I confirm the parcel contains no prohibited items.</label><button className="rounded-xl bg-[#0c312d] p-4 font-bold text-white sm:col-span-2">Create parcel booking</button></form>}</section>
  </div></main>;
}

function errorMessage(body: { message?: string; errors?: Record<string, string[]> }) { return Object.values(body.errors ?? {})[0]?.[0] ?? body.message ?? "Booking failed."; }
