"use client";

import { useEffect, useRef, useState } from "react";
import { platform } from "@/lib/platform";

export default function DriverPage() {
  const [token, setToken] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem("mufambi-token") ?? ""); const [tripId, setTripId] = useState(() => typeof window === "undefined" ? "" : localStorage.getItem("mufambi-driver-trip") ?? ""); const [active, setActive] = useState(false); const [message, setMessage] = useState("Location sharing is stopped."); const watchId = useRef<number | null>(null);
  useEffect(() => () => { if (watchId.current !== null) navigator.geolocation.clearWatch(watchId.current); }, []);
  function saveToken(value: string) { setToken(value); localStorage.setItem("mufambi-token", value); } function saveTrip(value: string) { setTripId(value); localStorage.setItem("mufambi-driver-trip", value); }
  function start() { if (!token || !tripId) { setMessage("Add your access token and assigned trip ID first."); return; } if (!navigator.geolocation) { setMessage("This device does not support GPS."); return; } setActive(true); setMessage("Connecting to GPS…"); watchId.current = navigator.geolocation.watchPosition(async (position) => { try { const response = await fetch(`${platform.apiUrl}/trips/${tripId}/locations`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, speed_kph: Math.max(0, (position.coords.speed ?? 0) * 3.6), heading: position.coords.heading === null ? null : Math.round(position.coords.heading), accuracy_m: position.coords.accuracy, recorded_at: new Date(position.timestamp).toISOString() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Location update failed."); setMessage(`Last update sent at ${new Date().toLocaleTimeString()}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to send location."); } }, (error) => setMessage(error.message), { enableHighAccuracy: true, maximumAge: 10000, timeout: 20000 }); }
  function stop() { if (watchId.current !== null) navigator.geolocation.clearWatch(watchId.current); watchId.current = null; setActive(false); setMessage("Location sharing is stopped."); }
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><div className="w-full max-w-lg rounded-[2rem] bg-[#0c312d] p-8 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Mufambi crew</p><h1 className="mt-3 text-4xl font-black">Driver location</h1><p className="mt-3 text-emerald-50/70">Share location only during your assigned active trip. Tracking stops immediately when you tap stop.</p><div className="mt-8 grid gap-4"><label className="text-sm font-bold">Access token<input type="password" value={token} onChange={(e) => saveToken(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-4 outline-none focus:border-emerald-400" /></label><label className="text-sm font-bold">Assigned trip ID<input inputMode="numeric" value={tripId} onChange={(e) => saveTrip(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-4 outline-none focus:border-emerald-400" /></label></div><div className="mt-8 grid place-items-center rounded-3xl bg-slate-950/50 p-10"><div className={`size-24 rounded-full border-[10px] ${active ? "animate-pulse border-emerald-400 bg-emerald-400/20" : "border-slate-700"}`} /><p className="mt-5 text-center text-sm text-slate-300">{message}</p></div><button onClick={active ? stop : start} className={`mt-6 w-full rounded-2xl p-5 text-lg font-black ${active ? "bg-red-500" : "bg-emerald-400 text-emerald-950"}`}>{active ? "Stop sharing" : "Start trip tracking"}</button></div></main>;
}
